#!/usr/bin/env python3
"""Generate FireRed Pokédex entries (category, height, weight, description pages) for Kanto 1-151.

Output: apps/client/lib/generated/pokedexEntries.ts
Requires the local FireRed ROM; only the generated TypeScript is versioned.
gPokedexEntries is located by Bulbasaur's category ("SEED") + height 7 / weight 69; stride is 0x24.
"""
import json
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rom_lib import DEX, ROM, ROOT, decode_text, ptr  # noqa: E402

GEN = ROOT / "apps" / "client" / "lib" / "generated"
STRIDE = 0x24


def encode(text):
    return bytes(0xBB + ord(c) - 65 for c in text) + b"\xff"


def find_table():
    pat = encode("SEED")
    i = -1
    while True:
        i = ROM.find(pat, i + 1)
        if i < 0:
            raise SystemExit("gPokedexEntries not found")
        if struct.unpack("<HH", ROM[i + 12:i + 16]) == (7, 69):
            return i - STRIDE  # entry 0


def clean(text):
    return " ".join(text.replace("\f", " ").replace("\n", " ").split())


def description_page(p):
    # Pages use hard line breaks; keep them so the box matches the ROM's wrapping.
    return [line.strip() for line in decode_text(p, 200).replace("\f", "\n").split("\n") if line.strip()]


FRONT = ROOT / "apps" / "client" / "public" / "game-assets" / "firered" / "pokemon" / "front" / "normal"
front_files = {int(f.name[:4]): f.name for f in FRONT.glob("*.png") if f.name[:4].isdigit()}

base = find_table()
out = {}
for n in range(1, 152):
    o = base + STRIDE * n
    category = decode_text(o, 12).strip()
    height, weight = struct.unpack("<HH", ROM[o + 12:o + 16])
    p1, p2 = struct.unpack("<II", ROM[o + 16:o + 24])
    unused, mon_scale, mon_offset, trainer_scale, trainer_offset = struct.unpack("<HHhHh", ROM[o + 24:o + 34])
    pages = [pg for pg in (description_page(ptr(p)) for p in (p1, p2) if ptr(p)) if pg]
    out[DEX[n]] = {
        "category": category,
        "height": height,  # decimetres
        "weight": weight,  # hectograms
        "pages": pages,
        "sprite": front_files.get(n),
        "monScale": mon_scale,
        "monOffset": mon_offset,
        "trainerScale": trainer_scale,
        "trainerOffset": trainer_offset,
    }

body = json.dumps(out, indent=1, ensure_ascii=False)
(GEN / "pokedexEntries.ts").write_text(
    "// Generated by tools/rom-data/generate-pokedex.py — do not edit by hand.\n"
    "export type PokedexRomEntry = {\n"
    "  category: string;\n"
    "  /** decimetres */\n  height: number;\n"
    "  /** hectograms */\n  weight: number;\n"
    "  pages: readonly (readonly string[])[];\n"
    "  /** file under /game-assets/firered/pokemon/front/normal/ */\n"
    "  sprite: string | null;\n"
    "  /** Size-comparison affine scale (256 = 1.0) and vertical offset for the Pokemon and the trainer silhouette. */\n"
    "  monScale: number;\n  monOffset: number;\n  trainerScale: number;\n  trainerOffset: number;\n"
    "};\n"
    "export const POKEDEX_ENTRIES: Readonly<Record<string, PokedexRomEntry>> = "
    + body + ";\n",
    encoding="utf-8",
)
print("entries:", len(out))
