#!/usr/bin/env python3
"""Generate field obstacles and static encounters for the Kanto mainland maps.

Output: apps/client/lib/generated/worldObstacles.ts
  CUT_TREES, STRENGTH_BOULDERS  (ROM object events: CUT_TREE / PUSHABLE_BOULDER)
  STATIC_POKEMON                (Snorlax, Zapdos, Articuno, Mewtwo)

Requires the local ROM extraction; only the generated TypeScript is versioned.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rom_lib import ROM, ROOT, WORLD  # noqa: E402

GEN = ROOT / "apps" / "client" / "lib" / "generated"
index = json.loads((ROOT / "tools" / "rom-data" / "generated-maps-index.json").read_text(encoding="utf-8"))
maps = {}
maps.update(index["existing"])
maps.update(index["new"])  # dir -> map id

STATIC = {
    "SNORLAX": "snorlax",
    "ZAPDOS": "zapdos",
    "ARTICUNO": "articuno",
    "MEWTWO": "mewtwo",
}

# ROM item id -> StoryKeyItemId (key items lying on the ground)
KEY_ITEMS = {351: "secret-key", 353: "gold-teeth", 355: "card-key", 356: "lift-key", 359: "silph-scope", 369: "tea"}

trees, boulders, statics, key_balls, silph_doors, slots = [], [], [], [], [], []
for d, map_id in sorted(maps.items()):
    path = WORLD / d / "world.json"
    if not path.exists():
        continue
    world = json.loads(path.read_text(encoding="utf-8"))
    if map_id.startswith("silph-co-"):
        # Card Key doors: 2x2 bg events whose script starts with `lockall; setvar 0x4001, n`
        groups = {}
        for bg in world["bg_events"]:
            off = bg.get("script_offset")
            if bg["kind"] == 0 and off and ROM[off:off + 4] == bytes([0x69, 0x16, 0x01, 0x40]):
                groups.setdefault(off, []).append([bg["x"], bg["y"]])
        for n, cells in enumerate(groups.values()):
            silph_doors.append({"id": f"{map_id}-door-{n + 1}", "mapId": map_id, "cells": sorted(cells)})
    # Game Corner slot machines: bg events whose script is `lockall; setvar 0x8004, n; special ...`
    for bg in world["bg_events"]:
        off = bg.get("script_offset")
        if bg["kind"] in (3, 4) and off and ROM[off:off + 4] == bytes([0x69, 0x16, 0x04, 0x80]):
            slots.append({"mapId": map_id, "x": bg["x"], "y": bg["y"], "machine": ROM[off + 4]})
    for o in world["objects"]:
        g = o.get("graphics_name") or ""
        if o["x"] < 0 or o["y"] < 0:
            continue
        entry = {"mapId": map_id, "x": o["x"], "y": o["y"]}
        if g == "ITEM_BALL" and o["script_offset"]:
            b = ROM[o["script_offset"]:o["script_offset"] + 6]
            if b[0] == 0x1A and (b[3] | (b[4] << 8)) in KEY_ITEMS:
                key_balls.append({**entry, "keyItem": KEY_ITEMS[b[3] | (b[4] << 8)]})
        if g == "CUT_TREE":
            trees.append(entry)
        elif g == "PUSHABLE_BOULDER":
            boulders.append(entry)
        elif g in STATIC:
            statics.append({**entry, "species": STATIC[g], "flag": o["flag_id"]})

out = ["// Generated by tools/rom-data/generate-world-obstacles.py — do not edit by hand."]
out.append("export type GeneratedObstacle = { mapId: string; x: number; y: number };")
out.append("export type GeneratedStaticPokemon = GeneratedObstacle & { species: string; flag: number };")
for name, rows in (("CUT_TREES", trees), ("STRENGTH_BOULDERS", boulders)):
    out.append(f"export const {name}: readonly GeneratedObstacle[] = {json.dumps(rows, indent=1)};")
out.append(f"export const STATIC_POKEMON: readonly GeneratedStaticPokemon[] = {json.dumps(statics, indent=1)};")
out.append(f"export const KEY_ITEM_BALLS: readonly (GeneratedObstacle & {{ keyItem: string }})[] = {json.dumps(key_balls, indent=1)};")
out.append(f"export const SILPH_DOORS: readonly {{ id: string; mapId: string; cells: readonly (readonly [number, number])[] }}[] = {json.dumps(silph_doors)};")
out.append(f"export const SLOT_MACHINES: readonly {{ mapId: string; x: number; y: number; machine: number }}[] = {json.dumps(slots)};")
(GEN / "worldObstacles.ts").write_text("\n".join(out) + "\n", encoding="utf-8")
print(len(slots), "slot machines,", len(silph_doors), "silph doors,", len(key_balls), "key item balls,", len(trees), "cut trees,", len(boulders), "boulders,", len(statics), "static pokemon")
