#!/usr/bin/env python3
"""Generate surf and fishing encounter tables (gWildMonHeaders) for Kanto maps.

Output: apps/client/lib/generated/worldWaterEncounters.ts
Requires the local ROM extraction; only the generated TypeScript is versioned.
"""
import json
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rom_lib import DEX, ROM, ROOT, WORLD, ptr  # noqa: E402

GEN = ROOT / "apps" / "client" / "lib" / "generated"
index = json.loads((ROOT / "tools" / "rom-data" / "generated-maps-index.json").read_text(encoding="utf-8"))
maps = {**index["existing"], **index["new"]}

SURF_WEIGHTS = [60, 30, 5, 4, 1]
# FireRed fishing: slots 0-1 Old Rod, 2-4 Good Rod, 5-9 Super Rod
FISH_GROUPS = {"old": (0, 2, [70, 30]), "good": (2, 5, [60, 20, 20]), "super": (5, 10, [40, 40, 15, 4, 1])}


def read_slots(table_ptr, count, weights):
    slots = []
    for k in range(count):
        lo, hi, sp = struct.unpack("<BBH", ROM[table_ptr + k * 4:table_ptr + k * 4 + 4])
        if not 1 <= sp <= 151 or not 1 <= lo <= hi <= 100:
            return None
        slots.append({"weight": weights[k], "species": DEX[sp], "level": (lo + hi) // 2})
    return slots


def read_info(info_ptr, count_weights):
    p = ptr(info_ptr)
    if p is None or p + 8 > len(ROM):
        return None
    rate = ROM[p]
    tp = ptr(struct.unpack("<I", ROM[p + 4:p + 8])[0])
    if tp is None or tp + 4 * len(count_weights) > len(ROM) or not 1 <= rate <= 100:
        return None
    return rate, tp


out = {}
for d, code in sorted(maps.items()):
    path = WORLD / d / "world.json"
    if not path.exists():
        continue
    j = json.loads(path.read_text(encoding="utf-8"))
    pat = bytes([j["group"], j["map_num"], 0, 0])
    i = -1
    while True:
        i = ROM.find(pat, i + 1)
        if i < 0:
            break
        if i + 20 > len(ROM):
            break
        land, water, rock, fish = struct.unpack("<IIII", ROM[i + 4:i + 20])
        entry = {}
        # validate at least one of the tables so random byte matches are ignored
        w = read_info(water, SURF_WEIGHTS) if water else None
        if w:
            slots = read_slots(w[1], 5, SURF_WEIGHTS)
            if slots:
                entry["surf"] = {"encounterRate": w[0], "slots": slots}
        f = read_info(fish, [0] * 10) if fish else None
        if f:
            rods = {}
            for name, (a, b, weights) in FISH_GROUPS.items():
                raw = read_slots(f[1] + a * 4, b - a, weights)
                if raw:
                    rods[name] = raw
            if len(rods) == 3:
                entry["fishing"] = {"encounterRate": f[0], **rods}
        if entry and (land == 0 or ptr(land) is not None):
            out[code] = entry
            break

body = json.dumps(out, indent=1)
(GEN / "worldWaterEncounters.ts").write_text(
    "// Generated by tools/rom-data/generate-world-water.py — do not edit by hand.\n"
    "export type WaterSlot = { weight: number; species: string; level: number };\n"
    "export type WaterEncounterEntry = {\n"
    "  surf?: { encounterRate: number; slots: readonly WaterSlot[] };\n"
    "  fishing?: { encounterRate: number; old: readonly WaterSlot[]; good: readonly WaterSlot[]; super: readonly WaterSlot[] };\n"
    "};\n"
    f"export const WATER_ENCOUNTERS: Readonly<Record<string, WaterEncounterEntry>> = {body};\n",
    encoding="utf-8",
)
print(len(out), "maps;", sum('fishing' in v for v in out.values()), "fishing;", sum('surf' in v for v in out.values()), "surf")
