#!/usr/bin/env python3
"""Generate packages/battle-engine/src/generated/evYield.ts: the Gen III / FireRed EV yield and catch rate of every Kanto species.

Source: packages/game-data/data/kanto-species.json (`evYield`, read from the ROM base stats by extract-kanto-data.py).
Only non-zero stats are written. Usage: python tools/rom-data/generate-ev-yields.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
species = json.loads((ROOT / "packages" / "game-data" / "data" / "kanto-species.json").read_text(encoding="utf-8"))
out = {}
for sid, s in sorted(species.items()):
    y = {stat: n for stat, n in s["evYield"].items() if n}
    if y:
        out[sid] = y
catch_rates = {sid: s["catchRate"] for sid, s in sorted(species.items())}
lines = [
    "// Generated by tools/rom-data/generate-ev-yields.py — do not edit by hand.",
    "/** FireRed EV yield of each species when defeated (only non-zero stats). */",
    "export const GENERATED_EV_YIELD: Readonly<Record<string, Readonly<Partial<Record<\"hp\" | \"attack\" | \"defense\" | \"speed\" | \"specialAttack\" | \"specialDefense\", number>>>>> = "
    + json.dumps(out, indent=1) + ";",
    "",
    "/** FireRed catch rate (3-255) of every Kanto species, read from the ROM base stats. */",
    "export const ROM_CATCH_RATE: Readonly<Record<string, number>> = " + json.dumps(catch_rates) + ";",
    "",
]
(ROOT / "packages" / "battle-engine" / "src" / "generated" / "evYield.ts").write_text("\n".join(lines), encoding="utf-8")
print(len(out), "species with an EV yield;", sum(sum(v.values()) for v in out.values()), "points in total")
