#!/usr/bin/env python3
"""Generate the competitive nature of each Kanto species from Smogon's Gen 3 sets.

Source: https://pkmn.github.io/smogon/data/sets/gen3.json (the pkmn/smogon export of Smogon's Gen 3
strategy dex: RSE/FRLG-era sets with a `nature` per set, a single name or a list in order of preference).
Output: apps/client/lib/generated/smogonNatures.ts

Per species the highest tier that has sets wins (ou, uu, ru, nu, pu, zu, then ubers / lc / doublesou);
inside it every set votes for its natures (first listed = 1 vote, later ones 0.5). The most voted is the
nature, the others of that tier are the alternatives. Species with no sets (mostly unevolved forms)
are left out: the client falls back to their evolution, then to a stat heuristic.
"""
import json
import re
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rom_lib import DEX, ROOT  # noqa: E402

URL = "https://pkmn.github.io/smogon/data/sets/gen3.json"
TIERS = ["ou", "uu", "ru", "nu", "pu", "zu", "ubers", "lc", "doublesou"]


def norm(name: str) -> str:
    return re.sub(r"[^a-z]", "", name.lower())


with urllib.request.urlopen(URL, timeout=60) as response:
    data = json.load(response)
by_norm = {norm(name): sets for name, sets in data.items()}

result = {}
for dex in range(1, 152):
    species = DEX[dex]
    sets_by_tier = by_norm.get(norm(species))
    if not sets_by_tier:
        continue
    tier = next((t for t in TIERS if t in sets_by_tier), None)
    if not tier:
        continue
    votes, order, source_set = {}, [], {}
    for set_name, spec in sets_by_tier[tier].items():
        natures = spec.get("nature")
        natures = natures if isinstance(natures, list) else [natures]
        for index, nature in enumerate(natures):
            if not nature:
                continue
            key = nature.lower()
            if key not in votes:
                order.append(key)
                source_set[key] = set_name
            votes[key] = votes.get(key, 0) + (1 if index == 0 else 0.5)
    if not votes:
        continue
    ranked = sorted(order, key=lambda k: (-votes[k], order.index(k)))
    result[species] = {"nature": ranked[0], "alternatives": ranked[1:3], "tier": tier, "set": source_set[ranked[0]]}

assert result["alakazam"]["nature"] in ("timid", "modest")
assert result["machamp"]["nature"] in ("adamant", "jolly")

out = ROOT / "apps" / "client" / "lib" / "generated" / "smogonNatures.ts"
out.write_text(
    "// Generated by tools/rom-data/generate-smogon-natures.py from Smogon's Gen 3 sets — do not edit by hand.\n"
    "export type SmogonNature = { nature: string; alternatives: readonly string[]; tier: string; set: string };\n"
    "export const SMOGON_NATURES: Readonly<Record<string, SmogonNature>> = "
    + json.dumps(result, indent=1, ensure_ascii=False) + " as const;\n",
    encoding="utf-8",
)
print(len(result), "species with Smogon Gen 3 sets")
