#!/usr/bin/env python3
"""Generate FireRed Pokédex orderings and habitat categories for Kanto 1-151.

Source: the pret/pokefirered decomp tables that are compiled into the ROM
(src/data/pokemon/pokedex_orders.h, pokedex_categories.h). They are used as a
data reference only; pass a directory that contains both files (downloaded
from the repository) as the first argument.

Output: apps/client/lib/generated/pokedexOrders.ts
  POKEDEX_ORDERS: { alphabetical, weight, height, type }  -> arrays of Kanto dex numbers
  POKEDEX_CATEGORIES: [{ id, pages: number[][] }]          -> habitat pages (Kanto species only, empty pages kept)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPECIES = json.loads((ROOT / "packages" / "game-data" / "data" / "kanto-species.json").read_text(encoding="utf-8"))
BY_TOKEN = {sid.upper().replace("-", "_"): int(v["dex"]) for sid, v in SPECIES.items() if 1 <= int(v["dex"]) <= 151}

src_dir = Path(sys.argv[1])
orders_src = (src_dir / "pokedex_orders.h").read_text(encoding="utf-8")
cats_src = (src_dir / "pokedex_categories.h").read_text(encoding="utf-8")


def kanto_numbers(body: str) -> list[int]:
    out = []
    for token in re.findall(r"(?:NATIONAL_DEX|SPECIES)_([A-Z0-9_]+)", body):
        if token in BY_TOKEN:
            out.append(BY_TOKEN[token])
    return out


orders = {}
for name, key in (("Alphabetical", "alphabetical"), ("Weight", "weight"), ("Height", "height"), ("Type", "type")):
    m = re.search(r"gPokedexOrder_" + name + r"\[\]\s*=\s*\{(.*?)\};", orders_src, re.S)
    nums = kanto_numbers(m.group(1))
    assert sorted(set(nums)) == list(range(1, 152)), (name, len(nums))
    orders[key] = nums

page_arrays = {
    m.group(1): kanto_numbers(m.group(2))
    for m in re.finditer(r"sDexCategory_(\w+_Page\d+)\[\]\s*=\s*\{(.*?)\};", cats_src, re.S)
}
# Full page sizes (including non-Kanto species) matter for page numbering in the ROM; keep them.
full_sizes = {
    m.group(1): len(re.findall(r"SPECIES_", m.group(2)))
    for m in re.finditer(r"sDexCategory_(\w+_Page\d+)\[\]\s*=\s*\{(.*?)\};", cats_src, re.S)
}

categories = []
for cat in ("GrasslandPkmn", "ForestPkmn", "WatersEdgePkmn", "SeaPkmn", "CavePkmn", "MountainPkmn", "RoughTerrainPkmn", "UrbanPkmn", "RarePkmn"):
    pages = []
    i = 1
    while f"{cat}_Page{i}" in page_arrays:
        pages.append(page_arrays[f"{cat}_Page{i}"])
        i += 1
    categories.append({"id": cat, "pages": pages})

out = ROOT / "apps" / "client" / "lib" / "generated" / "pokedexOrders.ts"
out.write_text(
    "// Generated by tools/rom-data/generate-dex-orders.py — do not edit by hand.\n"
    "export const POKEDEX_ORDERS = " + json.dumps(orders) + " as const;\n"
    "export const POKEDEX_CATEGORIES: readonly { id: string; pages: readonly (readonly number[])[] }[] = "
    + json.dumps(categories) + ";\n",
    encoding="utf-8",
)
print("orders:", {k: len(v) for k, v in orders.items()}, "categories:", [(c["id"], len(c["pages"]), sum(1 for p in c["pages"] if p)) for c in categories])
