#!/usr/bin/env python3
"""Generate which Kanto species can use each field HM (gTMHMLearnsets, FireRed).

Output: apps/client/lib/generated/hmCompat.ts
The table is located by signature (u64 per species: TM01-50 = bits 0-49, HM01-08 = bits 50-57)
and sanity-checked with well-known species (Charizard→Fly, Gyarados→Surf, Machamp→Strength).
"""
import json
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rom_lib import DEX, ROM, ROOT  # noqa: E402

HMS = {50: "cut", 51: "fly", 52: "surf", 53: "strength", 54: "flash", 55: "rock-smash"}


def entry(base, i):
    return struct.unpack("<Q", ROM[base + 8 * i:base + 8 * i + 8])[0]


def popcount(v):
    return bin(v).count("1")


candidates = [
    b for b in range(0x240000, 0x2B0000, 4)
    if entry(b, 0) == 0 and popcount(entry(b, 151)) >= 45 and popcount(entry(b, 129)) <= 3
    and (entry(b, 130) >> 52) & 1 and (entry(b, 6) >> 51) & 1
]
if len(candidates) != 1:
    sys.exit(f"gTMHMLearnsets signature ambiguous: {candidates}")
base = candidates[0]

compat = {}
for n in range(1, 152):
    mask = entry(base, n)
    moves = [name for bit, name in HMS.items() if (mask >> bit) & 1]
    if moves:
        compat[DEX[n]] = moves
assert "cut" in compat["bulbasaur"] and "surf" in compat["gyarados"] and "strength" in compat["machamp"]

GEN = ROOT / "apps" / "client" / "lib" / "generated"
(GEN / "hmCompat.ts").write_text(
    "// Generated by tools/rom-data/generate-hm-compat.py — do not edit by hand.\n"
    "export type FieldHmMove = \"cut\" | \"fly\" | \"surf\" | \"strength\" | \"flash\" | \"rock-smash\";\n"
    "export const HM_COMPAT: Readonly<Record<string, readonly FieldHmMove[]>> = "
    + json.dumps(compat, indent=1) + " as const;\n",
    encoding="utf-8",
)
print(len(compat), "species can use at least one field HM")
