#!/usr/bin/env python3
"""Generate the data behind the FireRed Pokédex area page (Kanto only).

- MAP_MAPSEC:        Tactimon map id -> ROM region-map section id (read from the extracted map headers)
- MAPSEC_TO_DEX_AREAS: region-map section id -> dex area names (wild_pokemon_area.c sDexAreas_Kanto)
- DEX_AREA_MARKERS:  dex area -> [marker shape, x, y] (pokedex_area_markers.c sAreaMarkers)

The pret/pokefirered decomp sources are only used as a reference for the two tables above
(pass a directory containing wild_pokemon_area.c, area_markers.c and region_map_sections.json).
Output: apps/client/lib/generated/pokedexAreas.ts
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ref = Path(sys.argv[1])
WORLD = ROOT / "local-assets" / "extracted" / "firered" / "assets" / "maps" / "world"

sections = [s["id"] for s in json.loads((ref / "region_map_sections.json").read_text(encoding="utf-8"))["map_sections"]]
sec_index = {name: i for i, name in enumerate(sections)}

wild = (ref / "wild_pokemon_area.c").read_text(encoding="utf-8")
body = re.search(r"sDexAreas_Kanto\[\]\[2\]\s*=\s*\{(.*?)\};", wild, re.S).group(1)
mapsec_areas: dict[int, list[str]] = {}
for sec, area in re.findall(r"\{\s*(MAPSEC_\w+)\s*,\s*(DEX_AREA_\w+)\s*\}", body):
    mapsec_areas.setdefault(sec_index[sec], []).append(area)

markers_src = (ref / "area_markers.c").read_text(encoding="utf-8")
marker_kinds = {
    "MARKER_CIRCULAR": 0, "MARKER_SMALL_H": 1, "MARKER_SMALL_V": 2, "MARKER_MED_H": 3,
    "MARKER_MED_V": 4, "MARKER_LARGE_H": 5, "MARKER_LARGE_V": 6,
}
markers = {}
for area, kind, x, y in re.findall(r"\[(DEX_AREA_\w+)\]\s*=\s*\{\s*(MARKER_\w+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\}", markers_src):
    markers[area] = [marker_kinds[kind], int(x), int(y)]

index = json.loads((ROOT / "tools" / "rom-data" / "generated-maps-index.json").read_text(encoding="utf-8"))
dir_to_id = {**index["existing"], **index["new"]}
hand = json.loads((ROOT / "tools" / "rom-data" / "hand-map-dirs.json").read_text(encoding="utf-8"))
if isinstance(hand, dict):
    dir_to_id.update({k: v for k, v in hand.items() if isinstance(v, str)})

map_mapsec = {}
for d, map_id in dir_to_id.items():
    p = WORLD / d / "world.json"
    if p.exists():
        map_mapsec[map_id] = json.loads(p.read_text(encoding="utf-8"))["region_map_section_id"]

out = ROOT / "apps" / "client" / "lib" / "generated" / "pokedexAreas.ts"
out.write_text(
    "// Generated by tools/rom-data/generate-dex-areas.py — do not edit by hand.\n"
    "/** Tactimon map id -> ROM region-map section id. */\n"
    "export const MAP_MAPSEC: Readonly<Record<string, number>> = " + json.dumps(map_mapsec, sort_keys=True) + ";\n"
    "/** Region-map section id -> Kanto dex areas (sDexAreas_Kanto). */\n"
    "export const MAPSEC_TO_DEX_AREAS: Readonly<Record<number, readonly string[]>> = " + json.dumps(mapsec_areas, sort_keys=True) + ";\n"
    "/** Dex area -> [marker shape 0..6, x, y] on the 96x72 Kanto map (sAreaMarkers). */\n"
    "export const DEX_AREA_MARKERS: Readonly<Record<string, readonly [number, number, number]>> = " + json.dumps(markers, sort_keys=True) + ";\n",
    encoding="utf-8",
)
print("maps:", len(map_mapsec), "mapsecs with areas:", len(mapsec_areas), "markers:", len(markers))
