#!/usr/bin/env python3
"""Generate which Kanto species learn each TM (TM01-TM50) and HM (HM01-HM08), FireRed.

Output: apps/client/lib/generated/tmCompat.ts
gTMHMLearnsets is located by the same signature generate-hm-compat.py uses (u64 per species:
TM01-50 = bits 0-49, HM01-08 = bits 50-57). The TM/HM move order is the fixed FireRed item order.
"""
import json
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rom_lib import DEX, ROM, ROOT  # noqa: E402

TMS = (
    "focus-punch dragon-claw water-pulse calm-mind roar toxic hail bulk-up bullet-seed hidden-power "
    "sunny-day taunt ice-beam blizzard hyper-beam light-screen protect rain-dance giga-drain safeguard "
    "frustration solar-beam iron-tail thunderbolt thunder earthquake return dig psychic shadow-ball "
    "brick-break double-team reflect shock-wave flamethrower sludge-bomb sandstorm fire-blast rock-tomb "
    "aerial-ace torment facade secret-power rest attract thief steel-wing skill-swap snatch overheat"
).split()
HMS = "cut fly surf strength flash rock-smash waterfall dive".split()
assert len(TMS) == 50 and len(HMS) == 8


def entry(base, i):
    return struct.unpack("<Q", ROM[base + 8 * i:base + 8 * i + 8])[0]


def popcount(v):
    return bin(v).count("1")


candidates = [
    b for b in range(0x240000, 0x2B0000, 4)
    if entry(b, 0) == 0 and popcount(entry(b, 151)) >= 45 and popcount(entry(b, 129)) <= 3
    and (entry(b, 130) >> 52) & 1 and (entry(b, 6) >> 51) & 1
]
if len(candidates) != 1:
    sys.exit(f"gTMHMLearnsets signature ambiguous: {candidates}")
base = candidates[0]

learns = {}
for n in range(1, 152):
    mask = entry(base, n)
    tms = [i + 1 for i in range(50) if (mask >> i) & 1]
    hms = [i + 1 for i in range(8) if (mask >> (50 + i)) & 1]
    if tms or hms:
        learns[DEX[n]] = {"tm": tms, "hm": hms}

# Sanity checks with well-known facts (TM29 Psychic: Alakazam yes, Machamp no; TM26 Earthquake: Rhydon).
assert 29 in learns["alakazam"]["tm"] and 29 not in learns["machamp"]["tm"]
assert 26 in learns["rhydon"]["tm"] and 24 in learns["pikachu"]["tm"]
assert 3 in learns["gyarados"]["hm"]
assert 31 in learns["machamp"]["tm"]  # Brick Break

GEN = ROOT / "apps" / "client" / "lib" / "generated"
(GEN / "tmCompat.ts").write_text(
    "// Generated by tools/rom-data/generate-tm-compat.py — do not edit by hand.\n"
    f"export const TM_MOVES: readonly string[] = {json.dumps(TMS)};\n"
    f"export const HM_MOVES: readonly string[] = {json.dumps(HMS)};\n"
    "/** Species -> TM numbers (1-50) and HM numbers (1-8) it can learn. */\n"
    "export const TM_COMPAT: Readonly<Record<string, { tm: readonly number[]; hm: readonly number[] }>> = "
    + json.dumps(learns, separators=(",", ":")) + " as const;\n",
    encoding="utf-8",
)
print(len(learns), "species learn at least one TM/HM")
