#!/usr/bin/env python3
"""Generate FireRed move descriptions (the 4-line text of the Summary move page).

The pret decomp (src/move_descriptions.c) is only a lookup: each description is encoded with the
Western charset and must be present in the local ROM; the text written out is that verified string.
Usage: python tools/rom-data/generate-move-descriptions.py <dir containing move_descriptions.c>
Output: apps/client/lib/generated/moveDescriptions.ts  (key = lowercase letters of the move name)
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from rom_lib import ROM, ROOT  # noqa: E402

src = (Path(sys.argv[1]) / "move_descriptions.c").read_text(encoding="utf-8")
charmap = {}
for line in (Path(sys.argv[1]) / "charmap.txt").read_text(encoding="utf-8").splitlines():
    m = re.match(r"^'(.+?)'\s*=\s*([0-9A-F]{2})\s*$", line)
    if m:
        charmap[m.group(1)] = int(m.group(2), 16)
charmap["'"] = 0xB4


def encode(text: str) -> bytes:
    out = bytearray()
    for ch in text:
        if ch == "\n":
            out.append(0xFE)
        elif ch.isupper() and ch.isascii():
            out.append(0xBB + ord(ch) - 65)
        elif ch.islower() and ch.isascii():
            out.append(0xD5 + ord(ch) - 97)
        elif ch.isdigit():
            out.append(0xA1 + int(ch))
        else:
            out.append(charmap[ch])
    return bytes(out) + b"\xff"


out = {}
missing = 0
for name, text in re.findall(r'gMoveDescription_(\w+)\[\]\s*=\s*_\("((?:[^"\\]|\\.)*)"\)', src):
    text = text.replace("\\n", "\n").replace('\\"', '"')
    try:
        found = ROM.find(encode(text)) >= 0
    except KeyError:
        found = False
    if not found:
        missing += 1
        continue
    out[re.sub(r"[^a-z]", "", name.lower())] = text
print(len(out), "descriptions verified in ROM,", missing, "not found")
(ROOT / "apps" / "client" / "lib" / "generated" / "moveDescriptions.ts").write_text(
    "// Generated by tools/rom-data/generate-move-descriptions.py — do not edit by hand.\n"
    "/** FireRed move descriptions keyed by the lowercase letters of the move name. */\n"
    "export const MOVE_DESCRIPTIONS: Readonly<Record<string, string>> = "
    + json.dumps(out, indent=1, ensure_ascii=False)
    + ";\n",
    encoding="utf-8",
)
