import { tx } from "./i18n";
/** Display names and descriptions for story key items (Bag → KEY ITEMS). */
export const KEY_ITEM_LABELS: Record<string, string> = {
  "oaks-parcel": "Oak's Parcel",
  "ss-ticket": "S.S. Ticket",
  "town-map": "Town Map",
  "old-amber": "Old Amber",
  "bike-voucher": "Bike Voucher",
  bicycle: "Bicycle",
  tea: "Tea",
  "silph-scope": "Silph Scope",
  "poke-flute": "Poké Flute",
  "card-key": "Card Key",
  "lift-key": "Lift Key",
  "secret-key": "Secret Key",
  "gold-teeth": "Gold Teeth",
  "coin-case": "Coin Case",
  "old-rod": "Old Rod",
  "good-rod": "Good Rod",
  "super-rod": "Super Rod",
};

export const KEY_ITEM_DESCRIPTIONS: Record<string, string> = {
  "oaks-parcel": tx("A parcel for Prof. Oak, from the Viridian City Poké Mart."),
  "ss-ticket": tx("A ticket to board the S.S. Anne in Vermilion City."),
  "town-map": tx("A map of Kanto given by Daisy."),
  "old-amber": tx("Ancient amber containing the DNA of a prehistoric Pokémon."),
  "bike-voucher": tx("Exchange it at the Cerulean Bike Shop for a Bicycle."),
  bicycle: tx("A Bicycle: it lets you move even faster (R toggles)."),
  tea: tx("Iced tea that the Saffron guard accepts in place of a pass."),
  "silph-scope": tx("A lens that reveals ghosts in the Pokémon Tower."),
  "poke-flute": tx("A flute that wakes sleeping Pokémon, like Snorlax."),
  "card-key": tx("A card that opens the locked doors of Silph Co."),
  "lift-key": tx("The key to the elevator in Team Rocket's hideout."),
  "secret-key": tx("The key to the door of the Cinnabar Island Gym."),
  "gold-teeth": tx("Gold teeth lost by the Safari Zone Warden."),
  "coin-case": tx("A case that holds up to 9,999 Game Corner coins."),
  "old-rod": tx("A simple fishing rod: hooks weak Pokémon."),
  "good-rod": tx("A fishing rod better than the Old Rod."),
  "super-rod": tx("The best fishing rod: it attracts rare Pokémon."),
};
