/** pt-BR for the generated Kanto sign lines (key = `mapId:x,y`). */
export const KANTO_SIGN_TEXT_PT: Readonly<
  Record<string, readonly string[]>
> = {
  "silph-co-1f:30,1": ["SILPH CO. MATRIZ 1F"],
  "silph-co-2f:29,1": ["SILPH CO. MATRIZ 2F"],
  "silph-co-3f:29,1": ["SILPH CO. MATRIZ 3F"],
  "silph-co-4f:29,1": ["SILPH CO. MATRIZ 4F"],
  "silph-co-5f:28,11": ["É um RELATÓRIO POKÉMON!", "Confirmou-se que alguns Pokémon evoluem quando são trocados."],
  "silph-co-5f:30,13": ["É um RELATÓRIO POKÉMON!", "Mais de 350 golpes Pokémon foram confirmados."],
  "silph-co-5f:25,15": ["É um RELATÓRIO POKÉMON!", "O Pokémon Lab criou o Porygon, o primeiro Pokémon de realidade virtual."],
  "silph-co-5f:29,1": ["SILPH CO. MATRIZ 5F"],
  "silph-co-6f:25,1": ["SILPH CO. MATRIZ 6F"],
  "silph-co-7f:20,1": ["SILPH CO. MATRIZ 7F"],
  "silph-co-8f:27,1": ["SILPH CO. MATRIZ 8F"],
  "silph-co-9f:17,1": ["SILPH CO. MATRIZ 9F"],
  "silph-co-10f:7,1": ["SILPH CO. MATRIZ 10F"],
  "silph-co-11f:8,1": ["SILPH CO. MATRIZ 11F"],
  "pokemon-mansion-2f:6,31": ["Diário: 10 de julho", "Batizamos o recém-descoberto Pokémon: Mew."],
  "pokemon-mansion-2f:25,4": ["Diário: 5 de julho", "Guiana, América do Sul…", "Um novo Pokémon foi descoberto no fundo da selva."],
  "pokemon-mansion-3f:8,16": ["Diário: 6 de fevereiro", "Mew deu à luz.", "Chamamos o recém-nascido de Mewtwo."],
  "pokemon-mansion-b-1f:21,27": ["Diário: 1º de setembro", "Mewtwo é poderoso demais.", "Fracassamos em conter suas tendências violentas…"],
  "safari-zone-center:30,26": ["CASA DE DESCANSO"],
  "safari-zone-east:43,15": ["CASA DE DESCANSO"],
  "safari-zone-north:44,9": ["CASA DE DESCANSO"],
  "safari-zone-west:22,19": ["CASA DE DESCANSO"],
  "safari-zone-center:25,27": ["DICAS DE TREINADOR", "Pressione START para ver o tempo restante."],
  "safari-zone-center:33,20": ["ÁREA CENTRAL"],
  "safari-zone-east:18,27": ["ÁREA 1 OESTE: ÁREA CENTRAL"],
  "safari-zone-east:17,8": ["DICAS DE TREINADOR", "O tempo restante só diminui enquanto você anda."],
  "safari-zone-north:13,27": ["DICAS DE TREINADOR", "A Casa Secreta ainda está mais à frente."],
  "safari-zone-north:23,31": ["ÁREA 2"],
  "safari-zone-north:29,32": ["DICAS DE TREINADOR", "Pokémon se escondem na grama alta.", "Ande em zigue-zague pela grama para fazê-los sair."],
  "safari-zone-north:34,28": ["DICAS DE TREINADOR", "Ganhe uma HM de graça por achar a Casa Secreta."],
  "safari-zone-west:27,9": ["AVISO DE PEDIDO", "Por favor, encontrem os Gold Teeth perdidos do Warden da Safari. Estão por aqui em algum lugar.", "Recompensa oferecida! Contato: Warden"],
  "safari-zone-west:36,10": ["DICAS DE TREINADOR", "Campanha de exploração da Zona! A busca pela Casa Secreta!"],
  "safari-zone-west:35,26": ["ÁREA 3 LESTE: ÁREA CENTRAL"],
  "rock-tunnel-1f:14,33": ["ROCK TUNNEL", "CERULEAN CITY - LAVENDER TOWN"],
  "seafoam-islands-b-4f:30,2": ["PERIGO", "Correnteza forte!"],
  "seafoam-islands-b-4f:14,18": ["Dica: Pedregulhos podem mudar o fluxo da água."],
  "lavender-town:12,4": ["Nova SILPH SCOPE! Torne o invisível visível!", "SILPH CO."],
  "lavender-town:15,11": ["LAVENDER TOWN", "A Nobre Cidade Roxa"],
  "lavender-town:21,7": ["POKÉMON TOWER", "Acalme os Espíritos dos Pokémon"],
  "lavender-town:7,11": ["CASA DOS VOLUNTÁRIOS POKÉMON DE LAVENDER"],
  "celadon-city:45,23": ["DICAS DE TREINADOR", "Guard Spec. protege os Pokémon de golpes que reduzem atributos durante a batalha.", "Compre seus itens na Celadon Dept. Store!"],
  "celadon-city:38,23": ["Troque Coins por prêmios!", "TROCA DE PRÊMIOS"],
  "celadon-city:33,23": ["ROCKET GAME CORNER", "O parque de diversões dos adultos!"],
  "celadon-city:22,18": ["CELADON CITY", "A Cidade dos Sonhos do Arco-Íris"],
  "celadon-city:26,11": ["CELADON MANSION"],
  "celadon-city:33,16": ["DICAS DE TREINADOR", "X Accuracy aumenta a precisão dos golpes.", "Dire Hit aumenta a chance de acertos críticos.", "Compre seus itens na Celadon Dept. Store!"],
  "celadon-city:18,14": ["Encontre o que precisa na CELADON DEPT. STORE!"],
  "celadon-city:16,31": ["CELADON CITY POKÉMON GYM", "LÍDER: ERIKA", "A Princesa Amante da Natureza!"],
  "fuchsia-city:31,18": ["FUCHSIA CITY", "Contemple! É o Rosa Apaixonado!"],
  "fuchsia-city:26,18": ["PARAÍSO POKÉMON", "SAFARI ZONE"],
  "fuchsia-city:5,32": ["FUCHSIA CITY POKÉMON GYM", "LÍDER: KOGA", "O Mestre Ninja Venenoso"],
  "fuchsia-city:31,31": ["CASA DO WARDEN DA SAFARI ZONE"],
  "fuchsia-city:35,10": ["Nome: VOLTORB", "A cara de uma Poké Ball."],
  "fuchsia-city:38,16": ["Nome: SLOWPOKE", "Simpático e muito lento."],
  "fuchsia-city:41,10": ["Nome: CHANSEY", "Capturar um depende totalmente da sorte."],
  "fuchsia-city:17,10": ["Nome: KANGASKHAN", "Um Pokémon maternal que cria os filhotes numa bolsa na barriga."],
  "fuchsia-city:11,10": ["Nome: KABUTO", "Um Pokémon raríssimo regenerado a partir de um fóssil."],
  "fuchsia-city:17,18": ["Nome: LAPRAS", "O rei dos mares."],
  "fuchsia-city:22,7": ["SAFARI GAME", "POKÉMON-U-CATCH!"],
  "cinnabar-island:12,3": ["CINNABAR ISLAND", "A Cidade Ardente do Desejo Flamejante"],
  "cinnabar-island:9,9": ["LABORATÓRIO POKÉMON"],
  "cinnabar-island:10,9": ["LABORATÓRIO POKÉMON"],
  "cinnabar-island:22,5": ["CINNABAR ISLAND POKÉMON GYM", "LÍDER: BLAINE", "O Mestre do Quiz Esquentado!"],
  "saffron-city:29,14": ["SAFFRON CITY", "Terra Dourada e Brilhante do Comércio"],
  "saffron-city:42,14": ["DOJO DE LUTA"],
  "saffron-city-dojo:3,13": ["DOJO DE LUTA"],
  "saffron-city-dojo:9,13": ["DOJO DE LUTA"],
  "saffron-city:13,25": ["O mais novo produto da SILPH! Lançamento a definir…"],
  "saffron-city:18,30": ["DICAS DE TREINADOR", "A nova Great Ball oferece taxas de captura melhores.", "Experimente nos Pokémon difíceis de capturar."],
  "saffron-city:29,31": ["EDIFÍCIO COMERCIAL DA SILPH CO."],
  "saffron-city:54,25": ["DICAS DE TREINADOR", "Full Heal cura todos os males, como queimadura, paralisia, envenenamento, congelamento e sono.", "Custa um pouco mais, mas é mais prático que comprar outros itens."],
  "saffron-city:50,14": ["SAFFRON CITY POKÉMON GYM", "LÍDER: SABRINA", "A Mestra dos Pokémon PSÍQUICOS!"],
  "saffron-city:40,38": ["CASA DO SR. PSYCHIC"],
  "saffron-city:49,22": ["FÃ-CLUBE DE TREINADORES POKÉMON", "Muitos Treinadores rabiscaram seus nomes nesta placa."],
  "route-7:5,14": ["UNDERGROUND PATH", "CELADON CITY - LAVENDER TOWN"],
  "route-8:16,5": ["UNDERGROUND PATH", "CELADON CITY - LAVENDER TOWN"],
  "route-9:29,7": ["ROUTE 9", "CERULEAN CITY - ROCK TUNNEL"],
  "route-10:15,59": ["ROCK TUNNEL"],
  "route-10:6,42": ["POWER PLANT"],
  "route-10:7,21": ["ROCK TUNNEL", "Desvio para LAVENDER TOWN"],
  "route-11:3,7": ["DIGLETT'S CAVE"],
  "route-12:17,13": ["ROUTE 12", "Ao norte: LAVENDER"],
  "route-12:15,69": ["ÁREA DE PESCA ESPORTIVA"],
  "route-13:41,12": ["ROUTE 13", "Ao norte: SILENCE BRIDGE"],
  "route-13:37,6": ["DICAS DE TREINADOR", "Use SELECT para trocar a ordem dos itens na janela de ITEMS."],
  "route-13:21,14": ["DICAS DE TREINADOR", "Olhe, olhe! Olhe à esquerda daquele poste!"],
  "route-14:17,12": ["ROUTE 14", "Ao oeste: FUCHSIA CITY"],
  "route-15:41,11": ["ROUTE 15", "Ao oeste: FUCHSIA CITY"],
  "route-16:6,17": ["ROUTE 16", "CELADON CITY - FUCHSIA CITY"],
  "route-16:33,11": ["Aproveite a ladeira!", "CYCLING ROAD"],
  "route-17:12,97": ["ROUTE 17", "CELADON CITY - FUCHSIA CITY"],
  "route-17:12,83": ["DICAS DE TREINADOR", "Pressione o botão B para ficar parado numa ladeira."],
  "route-17:12,68": ["DICAS DE TREINADOR", "Todos os Pokémon são únicos.", "Mesmo Pokémon da mesma espécie e nível crescem de formas diferentes."],
  "route-17:12,53": ["É um aviso.", "Cuidado com itens descartados."],
  "route-17:12,125": ["É um aviso!", "Não jogue o videogame, jogue Poké Balls!"],
  "route-17:11,157": ["CYCLING ROAD", "A ladeira termina aqui!"],
  "route-18:37,7": ["CYCLING ROAD", "Proibido pedestres!"],
  "route-18:52,7": ["ROUTE 18", "CELADON CITY - FUCHSIA CITY"],
  "route-19:13,12": ["ROTA MARÍTIMA 19", "FUCHSIA CITY - SEAFOAM ISLANDS"],
  "route-20:68,14": ["SEAFOAM ISLANDS"],
  "route-20:64,8": ["SEAFOAM ISLANDS"],
  "route-23:3,31": ["PORTÃO DA VICTORY ROAD", "POKÉMON LEAGUE"],
  "viridian-city-gym:15,20": ["VIRIDIAN POKÉMON GYM", "LÍDER: ?", "TREINADORES VENCEDORES: BLUE"],
  "viridian-city-gym:19,20": ["VIRIDIAN POKÉMON GYM", "LÍDER: ?", "TREINADORES VENCEDORES: BLUE"],
  "lavender-town-volunteer-pokemon-house:5,4": ["REVISTA DE FÃS DE POKÉMON", "Sorteio mensal do grande prêmio!", "O formulário de inscrição está…", "Sumiu! Foi recortado. Alguém já deve ter se inscrito."],
  "lavender-town-volunteer-pokemon-house:3,1": ["Revistas de Pokémon enchem a prateleira.", "POKÉMON INSIDER…", "POKÉMON FAN…"],
  "lavender-town-volunteer-pokemon-house:4,1": ["Revistas de Pokémon enchem a prateleira.", "POKÉMON INSIDER…", "POKÉMON FAN…"],
  "celadon-city-department-store-1f:9,11": ["1F: BALCÃO DE SERVIÇOS", "2F: MERCADO DO TREINADOR", "3F: LOJA DE VIDEOGAMES", "4F: PRESENTES DO SÁBIO", "5F: FARMÁCIA", "TERRAÇO: MÁQUINAS DE BEBIDAS"],
  "celadon-city-department-store-1f:8,1": ["1F: BALCÃO DE SERVIÇOS"],
  "celadon-city-department-store-2f:4,1": ["Itens de primeira para TREINADORES!", "2F: MERCADO DO TREINADOR"],
  "celadon-city-department-store-3f:8,1": ["3F: LOJA DE VIDEOGAMES"],
  "celadon-city-department-store-3f:1,8": ["É um Super NES."],
  "celadon-city-department-store-3f:1,11": ["É um Super NES."],
  "celadon-city-department-store-3f:4,8": ["É um Super NES."],
  "celadon-city-department-store-3f:4,11": ["É um Super NES."],
  "celadon-city-department-store-4f:4,1": ["Expresse-se com presentes!", "4F: PRESENTES DO SÁBIO", "Especial de Evolução! Pedras elementais em promoção!"],
  "celadon-city-department-store-5f:8,1": ["5F: FARMÁCIA"],
  "celadon-city-department-store-roof:14,3": ["TERRAÇO: MÁQUINAS DE BEBIDAS"],
  "celadon-city-condominiums-1f:8,12": ["CELADON MANSION", "Suíte do Gerente"],
  "celadon-city-condominiums-1f:7,12": ["CELADON MANSION", "Suíte do Gerente"],
  "celadon-city-condominiums-2f:8,12": ["GAME FREAK", "Sala de Reuniões"],
  "celadon-city-condominiums-2f:7,12": ["GAME FREAK", "Sala de Reuniões"],
  "celadon-city-condominiums-3f:8,12": ["GAME FREAK", "Sala de Desenvolvimento"],
  "celadon-city-condominiums-3f:7,12": ["GAME FREAK", "Sala de Desenvolvimento"],
  "celadon-city-condominiums-roof:4,12": ["EU SEI DE TUDO!"],
  "celadon-city-condominiums-roof:3,12": ["EU SEI DE TUDO!"],
  "celadon-city-condominiums-roof-room:4,1": ["PALESTRA POKÉMON", "Brincando com o Wireless Adapter"],
  "celadon-city-condominiums-roof-room:5,1": ["PALESTRA POKÉMON", "Brincando com o Wireless Adapter"],
  "celadon-city-condominiums-roof-room:4,4": ["É um panfleto sobre TMs.", "Há cinquenta TMs ao todo.", "Há também sete HMs que podem ser usadas repetidamente.", "SILPH CO."],
  "celadon-city-gym:4,16": ["CELADON POKÉMON GYM", "LÍDER: ERIKA", "TREINADORES VENCEDORES: BLUE"],
  "celadon-city-gym:8,16": ["CELADON POKÉMON GYM", "LÍDER: ERIKA", "TREINADORES VENCEDORES: BLUE"],
  "fuchsia-city-gym:4,19": ["FUCHSIA POKÉMON GYM", "LÍDER: KOGA", "TREINADORES VENCEDORES: BLUE"],
  "fuchsia-city-gym:10,19": ["FUCHSIA POKÉMON GYM", "LÍDER: KOGA", "TREINADORES VENCEDORES: BLUE"],
  "fuchsia-city-wardens-house:7,4": ["Mercadorias antigas de Pokémon estão em exposição."],
  "fuchsia-city-wardens-house:6,4": ["Mercadorias antigas de Pokémon estão em exposição."],
  "fuchsia-city-wardens-house:4,4": ["Fotos e fósseis de Pokémon estão em exposição."],
  "fuchsia-city-wardens-house:5,4": ["Fotos e fósseis de Pokémon estão em exposição."],
  "cinnabar-island-gym:23,20": ["CINNABAR POKÉMON GYM", "LÍDER: BLAINE", "TREINADORES VENCEDORES: BLUE"],
  "cinnabar-island-gym:27,20": ["CINNABAR POKÉMON GYM", "LÍDER: BLAINE", "TREINADORES VENCEDORES: BLUE"],
  "cinnabar-island-pokemon-lab-entrance:4,1": ["Uma foto do fundador do laboratório… DR. FUJI?!"],
  "cinnabar-island-pokemon-lab-entrance:12,5": ["LABORATÓRIO POKÉMON", "Sala de Reuniões"],
  "cinnabar-island-pokemon-lab-entrance:18,5": ["LABORATÓRIO POKÉMON", "Sala de P&D"],
  "cinnabar-island-pokemon-lab-entrance:24,5": ["LABORATÓRIO POKÉMON", "Sala de Testes"],
  "cinnabar-island-pokemon-lab-research-room:6,1": ["Um tubo de âmbar!"],
  "cinnabar-island-pokemon-lab-research-room:3,1": ["Há uma mensagem de e-mail.", "Existem três Pokémon lendários, aves.", "São Articuno, Zapdos e Moltres.", "Seu paradeiro é desconhecido.", "Planejamos explorar a caverna perto de Cerulean.", "De: Equipe de Pesquisa Pokémon…"],
  "saffron-city-copycats-house-2f:1,1": ["Meus Segredos!", "Habilidade: Imitação! Hobby: Colecionar bonecas! Pokémon favorito: CLEFAIRY!"],
  "saffron-city-copycats-house-2f:3,5": ["Um jogo com o Mario usando um balde na cabeça!"],
  "saffron-city-dojo:5,2": ["Inimigos por todos os lados!"],
  "saffron-city-dojo:7,2": ["O que vai, volta."],
  "saffron-city-gym:12,20": ["SAFFRON POKÉMON GYM", "LÍDER: SABRINA", "TREINADORES VENCEDORES: BLUE"],
  "saffron-city-gym:16,20": ["SAFFRON POKÉMON GYM", "LÍDER: SABRINA", "TREINADORES VENCEDORES: BLUE"],
  "saffron-city-house:5,4": ["Ganhei um PP Up de presente.", "Ele aumenta o PP de um golpe do Pokémon.", "Devo usá-lo num golpe poderoso com pouco PP."],
  "route-11-east-entrance-2f:4,1": ["Vamos ver o que o binóculo mostra…", "Um Pokémon enorme está dormindo na estrada!"],
  "route-11-east-entrance-2f:8,1": ["Vamos ver o que o binóculo mostra…", "Para ir de Cerulean City a Lavender Town…", "O Rock Tunnel parece uma boa rota."],
  "route-12-north-entrance-2f:4,1": ["Vamos ver o que o binóculo mostra…", "Há um homem pescando!"],
  "route-12-north-entrance-2f:8,1": ["Vamos ver o que o binóculo mostra…", "É a Pokémon Tower!"],
  "route-12-fishing-house:9,1": ["É uma tabela em branco de algum tipo.", "Tem espaços para anotar registros de algum tipo."],
  "route-15-west-entrance-2f:4,1": ["Vamos ver o que o binóculo mostra…", "Uma grande ave brilhante voa em direção ao mar."],
  "route-15-west-entrance-2f:8,1": ["Vamos ver o que o binóculo mostra…", "Parece uma pequena ilha no horizonte!"],
  "route-16-north-entrance-2f:4,1": ["Vamos ver o que o binóculo mostra…", "É a Celadon Dept. Store!"],
  "route-16-north-entrance-2f:8,1": ["Vamos ver o que o binóculo mostra…", "Há um longo caminho sobre a água ao longe."],
  "route-18-east-entrance-2f:4,1": ["Vamos ver o que o binóculo mostra…", "Pallet Town fica a oeste."],
  "route-18-east-entrance-2f:8,1": ["Vamos ver o que o binóculo mostra…", "Há pessoas nadando."],
};
